input = ["jplenqtlagxhivmwmscfukzodp",
"jbrehqtlagxhivmeyscfuvzodp",
"jbreaqtlagxzivmwysofukzodp",
"jxrgnqtlagxhivmwyscfukwodp",
"jbrenqtwagjhivmwysxfukzodp",
"jbrenqplagxhivmwyscfuazoip",
"jbrenqtlagxhivzwyscfldzodp",
"jbrefqtlagxhizmwyfcfukzodp",
"jbrenqtlagxhevmwfsafukzodp",
"jbrunqtlagxrivmsyscfukzodp",
"jbrenqtlaguhivmwyhlfukzodp",
"jbrcnstsagxhivmwyscfukzodp",
"jbrenqtlagozivmwyscbukzodp",
"jbrenqwlagxhivswysrfukzodp",
"jbrenstlagxhuvmiyscfukzodp",
"jbranqtlhgxhivmwysnfukzodp",
"jbrenqtvagxhinmxyscfukzodp",
"jbrenqtlagdhivmwyscfukxody",
"jbrenqtlagelavmwyscfukzodp",
"jbrenqtlagxhtvmwyhcfukzbdp",
"jbrenqwlagxhivmwyscfutzopp",
"jbrenqtlavxhibmtyscfukzodp",
"jbronqtlagxnivmwyscfuzzodp",
"jbredqtlagxhppmwyscfukzodp",
"jbrcnqtlogxhivmwysxfukzodp",
"jbremqtlagehivswyscfukzodp",
"jbrenqolagxhivmcyscfukzokp",
"jbrehqtlacxhgvmwyscfukzodp",
"fbrlnqtlagxhivmwyscbukzodp",
"zbrfnqtlagxhivrwyscfukzodp",
"jbregqtlagxnivmwyscfhkzodp",
"jbrenqtllgxnivmwystfukzodp",
"jurenqtlagxhivmwyscfulzoup",
"jbrenitdagxhivmwyxcfukzodp",
"jbrenqtlagxqivmwyscvuszodp",
"jbqenqwlagxhivmwyscfckzodp",
"jbrenqtlagxhivmwxscqupzodp",
"jbrenqtlagxhivmwysciuqiodp",
"jbrjnjtlagxhivmwyscfukzode",
"jbrenqtlagxhuvmwqscfukzods",
"jbrenqtlagxhuvmuyscfukzudp",
"ibrenqtlagxhivmwyscfuktokp",
"jbsenqtlagxhivcwyscfuksodp",
"jbrfnntlagxhivmwnscfukzodp",
"jzrenqulagxhivmwyscfukzodx",
"jbrenqtqygxhivmwyscfukzwdp",
"jbrenqtlagxfixmwyscfukzcdp",
"jbrenqaoagxhivmwyshfukzodp",
"jbrenqtlazxhivmworcfukzodp",
"jbrenqtlagxhicowyscfukrodp",
"jbrqnqtlagxhivzwyzcfukzodp",
"jbrenqtlalxhuvxwyscfukzodp",
"jbrenqtlqgxhhviwyscfukzodp",
"jbrenqtuggxhivmoyscfukzodp",
"jbrenqtlagxpivmwyscfukkodw",
"zbrenqhlagxhivmwyscdukzodp",
"jbrenutlagxxivmwyscfukzoqp",
"obrenqtlagxhivmwxscfuszodp",
"jbrenqtlagxhlvmwyscfuixodp",
"rbrenqtlagdhixmwyscfukzodp",
"jbrenqtlagxhivmwescfyszodp",
"jbrfnqtlagxhivmwyscaukzhdp",
"jbrenqtiagxhivmbyscfuxzodp",
"cbrrnqtuagxhivmwyscfukzodp",
"jbkenqtlagxhigmwysufukzodp",
"jbjewqtlagxhivmwyscfuqzodp",
"jbrznqtlagxvivmwyscfukzovp",
"jbrenttlacxhivmwyscfhkzodp",
"jblenqtlagxhivmwylcfukaodp",
"jbrenqtlagxhivmqysiftkzodp",
"jbrenqtlagwhikmwyscfukqodp",
"jbrenqtlegxhivmwvsckukzodp",
"jbrenqwzagxhiamwyscfukzodp",
"jbrenqtlagxhivcwyscfgkzodc",
"jbrenqtlagxxhvmwxscfukzodp",
"jbrenqtlngxhivmwyscfukoowp",
"jbreomtlagxhivmwpscfukzodp",
"jfrenqtlagxhivmwyscnumzodp",
"jbrenqtlagphipmwyscfukfodp",
"jvrenqtlagxhivmwyscfmkzodw",
"jbrenqtlaxxoiemwyscfukzodp",
"jbrenqtlagxhivmwyscemkzpdp",
"jbrenyjldgxhivmwyscfukzodp",
"jbrenqtlagxhivfvyspfukzodp",
"kbrenctlakxhivmwyscfukzodp",
"jbrmhqtlagxhivmwyscfuizodp",
"jbjenqtlagxlivmbyscfukzodp",
"jbrenqtlaaxhivmmyshfukzodp",
"jbronqtlagxhirmvyscfukzodp",
"jbcrnqtlagxwivmwyscfukzodp",
"jxrenszlagxhivmwyscfukzodp",
"jbpenqtlagxhivmwyscfukkody",
"jbrewqtlawxhivmwyscfukzhdp",
"jbrenqylagxhivmwlxcfukzodp",
"jbrenqtlagxxivtwywcfukzodp",
"jbrenqtlagxhcvgayscfukzodp",
"jbrenitlagxhivmwiscfukzohp",
"jbrenutlagxhivmwyscbukvodp",
"nbrenqtlagxhivmwysnfujzodp",
"jbrenqtlagxhivmwyqcfupzoop",
"jbrenqtrarxhijmwyscfukzodp",
"jbrenqtlagxhivmwysdfukzovy",
"jbrrnqtlagxhivmwyvcfukzocp",
"jbrenqtlagxhivmwyscfuvzzhp",
"jbhenitlagxhivmwysufukzodp",
"jbrenqtlagxhivmwyscfuwzoqx",
"kbrenqtlagxhivmwysqfdkzodp",
"jbrenqtlagxhivmwyxmfukzodx",
"jbcenatlagxxivmwyscfukzodp",
"jbrenhtlagvhdvmwyscfukzodp",
"jxrenqtlafxhivfwyscfukzodp",
"jbreaztlpgxhivmwyscfukzodp",
"tqrenqtlagxfivmwyscfukzodp",
"jbrenqgllgxhwvmwyscfukzodp",
"jbrejjtlagxhivmgyscfukzodp",
"jbrenqtlagxhivmwyscvukzoqv",
"jbrvnqtlagxsibmwyscfukzodp",
"jbrenqttagxhuvmwyscfukvodp",
"jbrenqteagxhivmwcscfukqodp",
"jbrenqtsabxhivmwyspfukzodp",
"jbbenqtlagxhivmwyscjukztdp",
"jnrenqtlagxhiimwydcfukzodp",
"jbrenqtlagxhfvmwyscxukzodu",
"jbrenqtluyxhiomwyscfukzodp",
"jbrenqvlagxhivmwyscuukzolp",
"ebrenqtlagxnivmwysrfukzodp",
"jbreeqtlatxhigmwyscfukzodp",
"jbrenqtvxgxhivmwyscfukzedp",
"jbrmnqtlagxhivmwywcfuklodp",
"jbreeqtvagxhivmwyscfukzody",
"jbrenptlagxhivmxyscfumzodp",
"jbrenqtlagxhivmwysgfukzfsp",
"jurenqtlagjhivmwkscfukzodp",
"jbrenntlagxhivmwtscffkzodp",
"jbrenqglagxhivmwyocfokzodp",
"wbrenqtlagxhivmwhscfukiodp",
"jbrenqtligxhivmqascfukzodp",
"jbrenqtlagxhivmwxscfukpojp",
"jurenqtlagxhivmmyscfbkzodp",
"jbrenqtmagxhivmwyscfrbzodp",
"jcrenqtlagxhivmwysefukzodm",
"jbrenqtlagxhicmwywcfukzodl",
"jbvanqtlagfhivmwyscfukzodp",
"jbmenqjlagxhivmwyscfdkzodp",
"jbrenqtlagohivvwysctukzodp",
"jbrenqtdagxdivmwyscfckzodp",
"kbrefqtlagxhivmwyscfuazodp",
"jbrwnqtoagxhivmwyswfukzodp",
"jjhenqtlagxhivmwyscfukzorp",
"jbgsnqtlagxhivkwyscfukzodp",
"jbrynqtlagxhivmsyspfukzodp",
"jbrenftlmkxhivmwyscfukzodp",
"nbrenqtxagxhmvmwyscfukzodp",
"jbrunqtlagxhijmwysmfukzodp",
"jbrenqtlagmaivmwyscfukzowp",
"jbrerqtlagxhihmwyscfukzudp",
"jbrenqtlagahivmwysckukzokp",
"kbrenqtlagxhirmwyscfupzodp",
"jbrrnqtlagxhivmwyecfukzodz",
"jbrenqtlavxhivmwyscfusiodp",
"jnrenqtlagxhivmwyhcfukzodw",
"jbretqtlagfhivmwyscfukzrdp",
"jbreoqtnagxhivmwyscfukzopp",
"jbrenbtllgxhivmwsscfukzodp",
"jbrenqtlmgxhivmwyscfuwzedp",
"jbnenqtlagxhivbwyscfukzokp",
"jbrenqslagxhivmvyscfukzndp",
"jbrenqtlagxzivmwuscfukztdp",
"gbrenqtlagxhyvmwyscfukjodp",
"jbrenqteagxhivmwyscfuszedp",
"jbrenqtlaglhivmwysafukkodp",
"jbrenqtlagxhcvmwascfukzogp",
"jbrenqtlagxhsvmkcscfukzodp",
"jbrenqslbgxhivmwyscfufzodp",
"cbrenqtlagxhivkwtscfukzodp",
"jbrenqtltgxhivmzyscfukzodj",
"jbrgnqtlagihivmwyycfukzodp",
"vbrenqauagxhivmwyscfukzodp",
"jbrqnqtlagjhivmwyscfqkzodp",
"jbrenqtlakxhivmwyscfukvobp",
"jcrenqelagxhivmwtscfukzodp",
"jbrrnqtlagxhlvmwyscfukzodw",
"jbrenqtlagxhivmwkscaumzodp",
"jbrenqdlagxhivmiescfukzodp",
"jhrenqtlagxhqvmwyscmukzodp",
"jbrenqtlaghhivmwyscfukkoyp",
"jowenqtlagxyivmwyscfukzodp",
"jbrenitaagxhivmwyscfqkzodp",
"jbrenqtlagxhivmwyscfnkbudp",
"jbyenqtlagxhivmiyscfukzhdp",
"jbrenitlagxhibjwyscfukzodp",
"jbrenqtlavxhjvmwpscfukzodp",
"jbrenqyaagxhivmwyscflkzodp",
"jbrenqylagxhivmwyicfupzodp",
"jbrenqtlagxmevmwylcfukzodp",
"lbrenqtlagxhiqmwyscfikzodp",
"jbrenqtnarxhivmwyscfmkzodp",
"jbrenqtlamxhivmwyscfnkzorp",
"jbbenqtlavxhivmwyscjukztdp",
"jbrenqtlagxhivmwyscfnliodp",
"jbwenetlagxhivmwyscfukzodt",
"jbrenatlagxhivmwysmfujzodp",
"jbrsnstlagxhivmwyscfukgodp",
"jbwvnitlagxhivmwyscfukzodp",
"jbrenqtbagxhkvmwypcfukzodp",
"jbrlnqtlafxhivmwyscfukdodp",
"jbrenztlanxhivmwyscjukzodp",
"jbrepqtlagxhivmwudcfukzodp",
"jbrenqtlagxiivmwdscfskzodp",
"jbrdjqtlagxhivmwyschukzodp",
"jbrenqtoaguhivmwyccfukzodp",
"jdrexqjlagxhivmwyscfukzodp",
"jbrenqtlagxhovmwysckukaodp",
"pbrfnqblagxhivmwyscfukzodp",
"jbrenqtlagxrivgiyscfukzodp",
"jbrelqtgagxhivmryscfukzodp",
"jbrenqtlagxhicmwjscfikzodp",
"jbrenqjlagxhivmwyscfmkjodp",
"jbrenqtlagxpivmwzscgukzodp",
"jbienqzlagxpivmwyscfukzodp",
"jbrenqvlagxhivmwdscfukzodx",
"owrenqtlagxhivmwyicfukzodp",
"gbrenqtlaathivmwyscfukzodp",
"jbgenqtlafxhivmwysqfukzodp",
"jbrenqtlagxhivtwsscfukzokp",
"jbrnnqylanxhivmwyscfukzodp",
"ebrenqolagxhivmcyscfukzodp",
"jbrenqtlarnhivgwyscfukzodp",
"jbmenqtlagxhivmvyscfukzgdp",
"jbrevqtlaglhivmwystfukzodp",
"jbrenqplanthivmwyscfukzodp",
"jbrenqtlagxhivmkyscbukzosp",
"jbrenqtlagxaivmwyscfugzodo",
"jbrenqplagxhnvmwyscfjkzodp",
"jbrenqtlagxhivgwyscfusrodp",
"cbrenqtlagxhivmwysmfukzody",
"jbrenquwaexhivmwyscfukzodp",
"jbredqtlagxhdvmwyscfukzoup",
"jbrxnqtlagxhivmwysczukaodp",
"jbrenqtlafnhivmwyscfuczodp",
"jbbdkqtlagxhivmwyscfukzodp",
"ubrenqtlagxhivkwyucfukzodp",
"ebjenqtlagxhivmwyscfukzodj",
"jbgenqtlugxxivmwyscfukzodp",
"jbrenqtoagxqivmwdscfukzodp",
"bbeenqtlagxhivmwyscfumzodp",
"jbfeeqtlagxhivmwmscfukzodp",
"jbrlnqtlagxhiimwescfukzodp",
"jbrenqtlagwoivmwyscfukhodp",
"jbrenqtlagnhivmwyscfuszovp"]


def calculate(words):
    letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p',
               'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']

    twoletters = 0
    threeletters = 0
    history2 = {}
    history3 = {}

    for word in input:
        history2[word] = False
        history3[word] = False

    for s in input:

        for char in range(26):
            if s.count(letters[char]) == 2:

                if history2[s]:
                    break
                else:
                    twoletters += 1
                    history2[s] = True

            elif s.count(letters[char]) == 3:

                if history3[s]:
                    break
                else:
                    threeletters += 1
                    history3[s] = True




    return twoletters * threeletters


print(calculate(input))




